### ISSUE TITLE
Update module help text

### ISSUE THREAD

**Issue by Connor-Bowley** [mturja-vf-ic-bd/SlicerDeepLearningUI#1]
Update the help text. If the text is empty, it will cause a failing test on the cdash dashboard.
https://github.com/mturja-vf-ic-bd/SlicerDeepLearningUI/blob/main/DeepLearner/DeepLearner.py#L29

**Comment by mturja-vf-ic-bd** [comment]
Updated

**Comment by Connor-Bowley** [comment]
Looks good, thanks.
