### ISSUE TITLE
Proper pip installs

### ISSUE THREAD

**Issue by Connor-Bowley** [mturja-vf-ic-bd/SlicerDeepLearningUI#3]
The user should not need to manually download python packages after installing via the extension index. You can install python packages programmatically in the following way:

```
try:
  import XYZ
except ImportError:
  slicer.util.pip_install('XYZ==1.0.0')
  import XYZ
```

Also, your list of packages includes `numpy==1.19.2`, Slicer master currently has `numpy==1.22.1` installed (see [here](https://github.com/Slicer/Slicer/blob/da8607855e2174d165a15352a42b86b3eb33d866/SuperBuild/External_python-numpy.cmake#L42)). Does this work with your application? If so, don't worry about numpy.

It is considered not the best practice to have the `try-import-except-install` block in the global space of the module itself, especially if the import could take a long time to download things. The reason this is not advised is because it could cause the slicer application to appear to hang during startup (because it is downloading things.

Looking at your particular setup, the following would probably work and be relatively simple.

1. In the global space of your ancillary files, do the `try-import-except-install` blocks.
2. In your main DeepLearner.py module file, do the `from src.training.EfficientNetTrainer import cli_main` inside the `process` function.

This will essentially hide the (potentially time taking) pip install in the already thought to be a long time taking training. Note the pip install would only ever happen on the first run after installing the extension.

**Comment by mturja-vf-ic-bd** [comment]
I have added `try-import-except-install` blocks for the ancillary files and added `from src.training.EfficientNetTrainer import cli_main` to the process function as you advised.

**Comment by Connor-Bowley** [comment]
Looks good. If you haven't already I would try rebuilding against a new build of Slicer and make sure that the installs work.

**Comment by mturja-vf-ic-bd** [comment]
Tested on a new slicer installation. It works fine.

**Comment by Connor-Bowley** [comment]
This works for me as well. Good work.
