### ISSUE TITLE
Rename src/ folder to DeepLearnerLib or _DeepLearnerLib

### ISSUE THREAD

**Issue by Connor-Bowley** [mturja-vf-ic-bd/SlicerDeepLearningUI#4]
Because of how Slicer is setup, all the modules and their ancillary Python files get bunched together in one massive folder. Due to this if someone else had a `src/` folder in their module, the contents of theirs and your would get thrown together in the same folder, which may cause issues.

To prevent this kind of thing, you should rename your `src/` folder to something more particular to the module name. My advice is to use `DeepLearnerLib` if the items inside it are meant (or allowable) to be used by other code than just the module (i.e. they are meant to be public classes and functions). If the code is meant to be private classes and functions, then I advise to use `_DeepLearnerLib`. The leading underscore [indicates in Python](https://docs.python.org/3/tutorial/classes.html#private-variables) that the variable/function/class is intended to be a private implementation detail.

**Comment by mturja-vf-ic-bd** [comment]
Changed the name to DeepLearningLib
